title: EasyPyro Help Documentation
description: User guides and product technical information. 
url: "https://docs.easypyro.com" # my custom domain
baseurl: "" # leave empty for custom domain
# theme: jekyll-theme-minimal
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme
  - jekyll-toc
relative_links:
  enabled: true
  collections: true
include: _pages